### ISSUE TITLE
[开发] 游戏背景设定，游戏故事脚本

### ISSUE THREAD

**Issue by kerocate** [Cuty-Room/AlgorithmGame#7]
目前主角粗略设定是：在某些情况下必须要将自己的行为梳理出来才能够执行

游戏背景：暂无

**Comment by Ylarod** [comment]
[大背景设定及主角设定](https://pwsg12okog.feishu.cn/docs/doccn7Hs0VuUaP6VxOENdOozVRg)

**Comment by kerocate** [comment]
大背景和游戏主角设定，通过。
